# Generated by Django 5.2.5 on 2025-09-08 14:50

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
